# Generated by Django 5.2.7 on 2025-10-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index_number', models.CharField(max_length=100, unique=True)),
                ('programme', models.CharField(max_length=255)),
                ('slip_number', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Not Collected', 'Not Collected'), ('Collected', 'Collected')], default='Not Collected', max_length=20)),
            ],
        ),
    ]
