# Generated by Django 5.2.7 on 2025-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterecord',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
