# Generated by Django 5.2.5 on 2026-01-26 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_certificaterecord_collected_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('UPLOAD', 'Upload Certificates'), ('COLLECT', 'Collect Certificate'), ('DOWNLOAD_REPORT', 'Download Report'), ('CREATE_USER', 'Create User'), ('EDIT_USER', 'Edit User'), ('DELETE_USER', 'Delete User'), ('RESET_PASSWORD', 'Reset Password'), ('SEARCH', 'Search Records')], help_text='Type of action performed', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_certificates', models.IntegerField(default=0)),
                ('collected_certificates', models.IntegerField(default=0)),
                ('pending_certificates', models.IntegerField(default=0)),
                ('total_uploads_today', models.IntegerField(default=0)),
                ('total_collections_today', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistics',
                'verbose_name_plural': 'Dashboard Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificaterecord',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Certificate Record', 'verbose_name_plural': 'Certificate Records'},
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this as collected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='department',
            field=models.CharField(help_text='Department/Faculty', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='index_number',
            field=models.CharField(help_text="Student's index/admission number", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='name',
            field=models.CharField(help_text="Student's full name", max_length=255),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='programme',
            field=models.CharField(help_text='Programme/Course name', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='slip_number',
            field=models.CharField(blank=True, help_text='Certificate/slip number', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['index_number'], name='registry_ce_index_n_a3b9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['status'], name='registry_ce_status_098125_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['-upload_date'], name='registry_ce_upload__febecb_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='certificate',
            field=models.ForeignKey(blank=True, help_text='Related certificate record (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='registry.certificaterecord'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='registry_ac_user_id_6665fa_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-timestamp'], name='registry_ac_action_55783e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='registry_ac_timesta_38e18f_idx'),
        ),
    ]
